Add textual description for graph 1
MassimiIiano/software-eng-projects-uni pull request #4
Opened 2024-10-13 12:45 UTC by dumbdannot

2024-10-13 21:41 UTC, Nicke44 requested changes

2024-10-13 21:41 UTC, Nicke44 commented on README.md
> +- Aufgabe 1: Das Anwendungsfalldiagramm zeigt das Autovermietungssystem, aus der Sicht des Kunden. Die angezeigte Anwendungsfälle beschreiben die Interaktionen zwischen den Kunden und dem System, dur
```suggestion
- Aufgabe 1: Das Anwendungsfalldiagramm zeigt das Autovermietungssystem aus der Sicht des Kunden. Die angezeigten Anwendungsfälle beschreiben die Interaktionen zwischen dem Kunden und dem System, durch Datenaustausch und dessen Anforderungen. Die Eintrittspunkte des Systems für den Kunden sind die Buchungen und die angezeigten Angebote. Jeder Anwendungsfall ist erforderlich für ein funktionsfähiges und komplettes Autovermietungssystem.
```

2024-10-13 21:41 UTC, Nicke44 commented on README.md
> +- Aufgabe 1: Das Anwendungsfalldiagramm zeigt das Autovermietungssystem, aus der Sicht des Kunden. Die angezeigte Anwendungsfälle beschreiben die Interaktionen zwischen den Kunden und dem System, dur
funktionsfähiges = funzionante

2024-10-14 11:40 UTC, MassimiIiano approved these changes
sembra ok

2024-10-15 18:30 UTC, Nicke44 approved these changes

2024-10-15 18:30 UTC, merged