Added aufgabe 5
MassimiIiano/software-eng-projects-uni pull request #7
Opened 2024-10-18 09:06 UTC by Nicke44

Ho cambiato la notazione dell'aufgabe 5, da mantenere consistente con aufgabe 6 in tedesco. Sistemato la grafica e aggiunto la descrizione del diagramma.

2024-10-20 15:05 UTC, dumbdannot requested changes

2024-10-20 15:05 UTC, dumbdannot commented on sw-eng-05.drawio.svg
I am fairly sure you cannot return a function for `zeigeMietvorschläge()`, as it's not data. The rest looks fine.

2024-10-20 16:11 UTC, Nicke44 commented on sw-eng-05.drawio.svg
Cancello la funzione di ritorno, allora lo interpretiamo come un metodo “grafico” che non ritorna niente ma fa cambia la view utente, lo scrivo nella descrizione

2024-10-21 11:40 UTC, MassimiIiano approved these changes
sembra aposto

2024-10-21 11:45 UTC, merged